### ISSUE TITLE
Collaboration / duplicate repos

### ISSUE THREAD

**Issue by jrfnl** [mjangda/plugin-notes#4]
Hi guys,

Glad to see the official version on GitHub!

As @mjangda and me discussed over mail some time back I've done some work on the plugin a while back. I never had the time to actually properly finish the last revision, but the work I'd done up to that point might well be worth incorporating now.

You can find the repo with the code here: https://github.com/jrfnl/WP-plugin-notes - not a fork as I put this online way before you created this repo, so that makes it difficult to merge and send PRs.

While the last revision might not have been finished, I did finish two earlier revisions (tagged as 1.5 and 1.6).
This is the changelog for those:

```
= 2012-12-18 / 1.6 by jrf =
* [_New feature_] Added ability to change the background color of notes

= 2012-12-16 / 1.5 by jrf =
* General code review
* [_Security_] Improved output escaping
* [_Bug fix_] Fixed AJAX delete bug (kept 'waiting')
* [_Bug fix_] Fixed note edit capability bug for when 'edit_plugins' capability has been removed for security reasons
* [_New feature_] Added output filters for html output (`plugin_notes_row` and `plugin_notes_form`) and the note itself (`plugin_notes_note`)
* [_New feature_] Added ability to use a number of variables in notes which will automagically be replaced - see [FAQ](http://wordpress.org/extend/plugins/plugin-notes/faq/) for more info
* [_New feature_] Added ability to use markdown syntax in notes - see [FAQ](http://wordpress.org/extend/plugins/plugin-notes/faq/) for more info
* [_Usability improvement_] Added `<hr />` to allowed tags list
* [_Usability improvement_] Made the default text area for adding a note larger
* [_Usability improvement_] Added automagical target="_blank" to all links in plugin notes including external link indicator
* [_Usability improvement_] Added contextual help for WP 3.3+
* [_Usability improvement_] Added FAQ section and plugin license info to the readme file ;-)
* [_Usability improvement_] Added uninstall script for clean uninstall of the plugin
* [_I8n_] Created .POT file and added Dutch translation
```

And this is the changelog /road map for what I was working on - most important highlights:
- multiple notes per plugin
- import/export ability
- private notes

```
= 2013-02-28 / 2.0 by jrf =
PLEASE NOTE: Once you upgrade, you can no longer downgrade without losing your notes!

* General improvements in code, query efficiency and security + code documentation
* [_Bug fix_] 'busy' image not loading when on a multi-site setup
* [_Bug fix_] displayed save date is now properly localized (for dates upgraded to/saved in the timestamp format - upgrade routine included)
* [_Bug fix_] Fixed: AJAX localization
* [_Clean code_] Cleaned up the HTML output
* [_Clean code_] Un-obtrusified the javascript handlers
* [_New feature_] Enabled multiple notes per plugin
* [_New feature_] Added auto-save of version number of the plugin a note applies to
//* [_New feature_] Added option to keep certain notes private: for your eyes only
* [_New feature_] Added admin screen for import/export/purge functionality and override of some option defaults
* [_New feature_] Added import/export functionality
//* [_New feature_] Added option to selectively exclude certain notes from export
* [_New feature_] Added purge functionality
//* [_New feature_] Added export plugin list as text file functionality
//* Added screen options with js show/hide mechanism for notes
* [_Usability improvement_] Change note date saving from formatted date to timestamp to facilitate changes in the date formatting options and date compare on import of notes
* [_Usability improvement_] Added an easy way to change the allowed html tags list
* [_Usability improvement_] Updated the FAQ information in the readme file
* [_Compatibility_] Added plugin notes version number to options to enable upgrade routine
* [_Compatibility_] Added upgrade routine for the new array structure of the plugin options
* [_Compatibility_] Added upgrade routine for new way of saving note date
* [_Compatibility_] Made contextual help available for WP < 3.3
* [_l18n_] Updated the .POT file for new strings & updated the Dutch translation
```

Hope this helps!

Smile,
Juliette

**Comment by cdillon** [comment]
Hi Juliette,

Thanks for reaching out. We have some decisions to make. How would you like to be involved going forward? 

Being a solo developer way before the days of pull requests, I can deftly handle manual merges of 1.5 and 1.6 to bring the main repo up to date. Version 2.0 looks very interesting and I'm looking forward to trying it out.

Chris

**Comment by jrfnl** [comment]
@cdillon Hi Chris, sorry for my slow response. I'd love to stay involved with Plugin Notes and contribute to it, but as you might have surmised I'm quite busy with other projects at this moment.

The code for 1.5 and 1.6 is out there already and I know a number of people are already using it, having found it via support issues in the repo where I mention it.

The code for v2 is largely still local and needs quite some work still to be usable. v2 is close to a complete rewrite/refactor, while the earlier tags build onto what was there.

Will you be adding a `develop` branch here for PRs with `master` being the released version ?

I might try and send in PRs for the v1.5/1.6 work some time over the next weeks if you like.
